import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const variants = ['mocha', 'latte', 'nord', 'solarized', 'dracula', 'gruvbox'];
const requiredTokens = [
  '--witzi-bg',
  '--witzi-bg-rgb',
  '--witzi-surface',
  '--witzi-surface-rgb',
  '--witzi-border',
  '--witzi-border-rgb',
  '--witzi-text',
  '--witzi-muted',
  '--witzi-accent',
  '--witzi-accent-rgb',
  '--witzi-accent-alt',
  '--witzi-accent-alt-rgb',
  '--witzi-correct-rgb',
  '--witzi-wrong-rgb',
  '--witzi-pattern'
];

const checkOnly = process.argv.includes('--check');
const basePath = resolve(projectRoot, 'src/witzi-base.css');
const base = readFileSync(basePath, 'utf8').replaceAll('\r\n', '\n').trim();
const problems = [];

function colorToken(css, token) {
  const match = css.match(new RegExp(`${token}:\\s*(#[0-9a-fA-F]{3,6})\\s*;`));
  return match?.[1];
}

function relativeLuminance(hex) {
  const expanded = hex.length === 4
    ? [...hex.slice(1)].map((digit) => `${digit}${digit}`).join('')
    : hex.slice(1);
  const [red, green, blue] = [0, 2, 4]
    .map((offset) => Number.parseInt(expanded.slice(offset, offset + 2), 16) / 255)
    .map((channel) => channel <= 0.03928
      ? channel / 12.92
      : ((channel + 0.055) / 1.055) ** 2.4);
  return (0.2126 * red) + (0.7152 * green) + (0.0722 * blue);
}

function contrastRatio(first, second) {
  const values = [relativeLuminance(first), relativeLuminance(second)].sort((a, b) => b - a);
  return (values[0] + 0.05) / (values[1] + 0.05);
}

function assertContrast(css, foregroundToken, backgroundToken, variant) {
  const foreground = colorToken(css, foregroundToken);
  const background = colorToken(css, backgroundToken);
  if (!foreground || !background) {
    problems.push(`${variant} cannot check ${foregroundToken} against ${backgroundToken}`);
    return;
  }
  const ratio = contrastRatio(foreground, background);
  if (ratio < 4.5) {
    problems.push(`${variant} ${foregroundToken}/${backgroundToken} contrast is ${ratio.toFixed(2)}:1`);
  }
}

function assertBalancedBraces(css, label) {
  let depth = 0;
  let quote = '';
  let inComment = false;

  for (let index = 0; index < css.length; index += 1) {
    const character = css[index];
    const next = css[index + 1];

    if (inComment) {
      if (character === '*' && next === '/') {
        inComment = false;
        index += 1;
      }
      continue;
    }

    if (!quote && character === '/' && next === '*') {
      inComment = true;
      index += 1;
      continue;
    }

    if (quote) {
      if (character === '\\') {
        index += 1;
      } else if (character === quote) {
        quote = '';
      }
      continue;
    }

    if (character === '"' || character === "'") {
      quote = character;
    } else if (character === '{') {
      depth += 1;
    } else if (character === '}') {
      depth -= 1;
      if (depth < 0) break;
    }
  }

  if (depth !== 0 || quote || inComment) {
    problems.push(`${label} has unbalanced CSS structure`);
  }
}

function createBundle(variant) {
  const palettePath = resolve(projectRoot, `src/palettes/${variant}.css`);
  const patternPath = resolve(projectRoot, `assets/pattern-${variant}.svg`);
  const pattern = readFileSync(patternPath, 'utf8').replaceAll('\r\n', '\n').trim();
  const embeddedPattern = `data:image/svg+xml;base64,${Buffer.from(pattern).toString('base64')}`;
  const palette = readFileSync(palettePath, 'utf8')
    .replaceAll('\r\n', '\n')
    .trim()
    .replace(
      new RegExp(`url\\(["']?\\.\\./\\.\\./assets/pattern-${variant}\\.svg["']?\\)`),
      `url("${embeddedPattern}")`
    );

  for (const token of requiredTokens) {
    if (!palette.includes(`${token}:`)) {
      problems.push(`${variant} is missing ${token}`);
    }
  }

  for (const [foreground, background] of [
    ['--witzi-text', '--witzi-bg'],
    ['--witzi-text', '--witzi-surface'],
    ['--witzi-muted', '--witzi-bg'],
    ['--witzi-muted', '--witzi-surface'],
    ['--witzi-on-accent', '--witzi-accent'],
    ['--witzi-on-accent-alt', '--witzi-accent-alt'],
    ['--witzi-on-wrong', '--witzi-wrong']
  ]) {
    assertContrast(palette, foreground, background, variant);
  }

  const banner = `/* Witzi for Jellyfin — ${variant}\n * Generated by npm run build. Edit src/, not this file.\n */`;
  return `${banner}\n\n${palette}\n\n${base}\n`;
}

assertBalancedBraces(base, 'src/witzi-base.css');

for (const variant of variants) {
  const bundle = createBundle(variant);
  const outputPath = resolve(projectRoot, `dist/witzi-${variant}.css`);
  const patternPath = resolve(projectRoot, `assets/pattern-${variant}.svg`);

  assertBalancedBraces(bundle, `dist/witzi-${variant}.css`);
  if (bundle.includes('@import')) {
    problems.push(`dist/witzi-${variant}.css unexpectedly contains @import`);
  }
  if (bundle.includes('../assets/')) {
    problems.push(`dist/witzi-${variant}.css contains a non-standalone asset path`);
  }
  if (!bundle.includes('data:image/svg+xml;base64,')) {
    problems.push(`dist/witzi-${variant}.css does not contain an embedded pattern`);
  }
  if (!existsSync(patternPath)) {
    problems.push(`missing ${patternPath}`);
  }

  if (checkOnly) {
    const current = existsSync(outputPath)
      ? readFileSync(outputPath, 'utf8').replaceAll('\r\n', '\n')
      : '';
    if (current !== bundle) {
      problems.push(`dist/witzi-${variant}.css is not up to date`);
    }
  } else {
    writeFileSync(outputPath, bundle, 'utf8');
    process.stdout.write(`built dist/witzi-${variant}.css\n`);
  }
}

if (problems.length > 0) {
  for (const problem of problems) process.stderr.write(`error: ${problem}\n`);
  process.exitCode = 1;
} else if (checkOnly) {
  process.stdout.write(`checked ${variants.length} theme bundles\n`);
}
