/**
 * Witzi browser helper for Jellyfin Web.
 *
 * Jellyfin builds Continue Watching and Next Up with landscape artwork. CSS
 * cannot change the API-selected image URL, so this optional helper asks the
 * current Jellyfin ApiClient for each card's metadata and swaps in a real
 * poster. Episodes use only their own portrait Primary poster (including one
 * generated by the Witzi server plugin); series, season, and parent artwork is
 * never substituted over it. Widescreen Primary captures are rejected. The
 * episode Primary must load successfully before it replaces Jellyfin's native
 * artwork, which remains visible as the fallback.
 *
 * The helper also keeps the last loaded backdrop in a two-layer cache outside
 * Jellyfin's backdrop container. Jellyfin clears that container between some
 * views, so the independent layers preserve the current image while the next
 * one loads, then crossfade without exposing the solid page background.
 */
(function witziPosterHelper() {
  'use strict';

  if (window.__witziPosterHelperLoaded) return;
  // Reserve initialization immediately. Jellyfin loads this inline helper
  // before its deferred application bundles and user Custom CSS, so another
  // injected copy must not win the race while we wait for the theme.
  window.__witziPosterHelperLoaded = true;

  const CARD_SCOPE_SELECTOR = '.itemsContainer[data-monitor*="videoplayback"][data-monitor*="markplayed"]';
  const CARD_SELECTOR = `${CARD_SCOPE_SELECTOR} .card[data-id]`;
  const CARD_LAYOUT_SELECTOR = [
    CARD_SELECTOR,
    `${CARD_SELECTOR} .cardImageContainer`,
    `${CARD_SELECTOR} .cardImageContainer img`
  ].join(', ');
  const BACKDROP_SELECTOR = '.backdropContainer';
  const DETAIL_PAGE_SELECTOR = '#itemDetailPage';
  const DETAIL_LAYOUT_PARENT_SELECTOR = [
    DETAIL_PAGE_SELECTOR,
    `${DETAIL_PAGE_SELECTOR} .detailRibbon`,
    `${DETAIL_PAGE_SELECTOR} .detailPagePrimaryContent`
  ].join(', ');
  const DETAIL_LAYOUT_SELECTOR = [
    DETAIL_LAYOUT_PARENT_SELECTOR,
    `${DETAIL_PAGE_SELECTOR} .infoWrapper`,
    `${DETAIL_PAGE_SELECTOR} .mainDetailButtons`,
    `${DETAIL_PAGE_SELECTOR} .detailSectionContent`,
    `${DETAIL_PAGE_SELECTOR} .itemDetailsGroup`
  ].join(', ');
  const DETAIL_RIBBON_ALIGN_OFFSET = '--witzi-detail-ribbon-align-offset';
  const THEME_WAIT_INITIAL_MS = 250;
  const THEME_WAIT_MAX_MS = 5000;
  const itemCache = new Map();
  const retryAfter = new Map();
  const pendingCards = new WeakSet();
  const alignedDetailRibbons = new WeakSet();
  const MISSING_RETRY_MS = 30000;
  const POSTER_LOAD_TIMEOUT_MS = 8000;
  const BACKDROP_LOAD_TIMEOUT_MS = 12000;
  const BACKDROP_TRANSITION_MS = 900;
  const backdropState = {
    activeIndex: -1,
    activeUrl: null,
    cache: null,
    cleanupTimer: null,
    layers: [],
    pendingUrl: null,
    requestId: 0
  };
  let retryTimer;
  let backdropScheduled = false;
  let cardScheduled = false;
  let detailScheduled = false;
  let playbackScheduled = false;
  let started = false;
  let themeWaitAttempts = 0;
  let themeWaitTimer;
  let videoPlaybackActive = false;

  function getApiClient() {
    return window.ApiClient || null;
  }

  function ownPoster(item) {
    const tag = item?.ImageTags?.Primary;
    const aspect = Number(item?.PrimaryImageAspectRatio);
    const isLandscapeFrame = Number.isFinite(aspect) && aspect > 1;
    return tag && item.Id && !isLandscapeFrame ? { id: item.Id, tag } : null;
  }

  function posterUrl(api, poster) {
    const options = {
      type: 'Primary',
      maxWidth: 600,
      quality: 90
    };

    if (poster.tag) options.tag = poster.tag;

    return typeof api.getScaledImageUrl === 'function'
      ? api.getScaledImageUrl(poster.id, options)
      : api.getImageUrl(poster.id, options);
  }

  async function fetchItems(api, ids) {
    const userId = api.getCurrentUserId?.();
    if (!userId || typeof api.getItems !== 'function') {
      throw new Error('Jellyfin ApiClient is not ready');
    }

    const response = await api.getItems(userId, {
      Ids: ids.join(','),
      Fields: 'PrimaryImageAspectRatio,ParentId',
      EnableImages: true,
      EnableImageTypes: 'Primary',
      ImageTypeLimit: 1
    });

    return response?.Items || [];
  }

  function canLoad(url, timeoutMs = POSTER_LOAD_TIMEOUT_MS) {
    return new Promise((resolve) => {
      const image = new Image();
      let settled = false;

      const finish = (loaded) => {
        if (settled) return;
        settled = true;
        window.clearTimeout(timeout);
        image.onload = null;
        image.onerror = null;
        resolve(loaded);
      };

      const timeout = window.setTimeout(() => finish(false), timeoutMs);
      image.onload = () => finish(true);
      image.onerror = () => finish(false);
      image.src = url;
    });
  }

  async function firstLoadablePoster(api, candidates) {
    for (const poster of candidates) {
      const url = posterUrl(api, poster);
      if (await canLoad(url)) return url;
    }

    return null;
  }

  async function resolvePosters(api, typeHints) {
    const ids = [...typeHints.keys()];
    const now = Date.now();
    const missingIds = ids.filter((id) => (
      !itemCache.has(id) && now >= (retryAfter.get(id) || 0)
    ));

    if (missingIds.length) {
      const items = await fetchItems(api, missingIds);
      const itemsById = new Map(items.map((item) => [item.Id, item]));

      await Promise.all(missingIds.map(async (id) => {
        const item = itemsById.get(id);
        const own = item && ownPoster(item);
        const candidates = own ? [own] : [];
        const url = await firstLoadablePoster(api, candidates);

        if (url) {
          itemCache.set(id, url);
          retryAfter.delete(id);
        } else {
          retryAfter.set(id, Date.now() + MISSING_RETRY_MS);
        }
      }));
    }

    return new Map(ids.map((id) => [id, itemCache.get(id) || null]));
  }

  function applyPoster(card, url) {
    const image = card.querySelector('.cardImageContainer');
    if (!image) return false;

    image.setAttribute('data-src', url);
    image.removeAttribute?.('data-blurhash');
    image.classList?.remove('lazy');
    image.style.backgroundImage = `url("${url.replace(/["\\]/g, '\\$&')}")`;
    image.style.backgroundPosition = 'center';
    image.style.backgroundRepeat = 'no-repeat';
    image.style.backgroundSize = 'cover';

    const nestedImage = image.querySelector('img');
    if (nestedImage) {
      nestedImage.src = url;
      nestedImage.removeAttribute?.('srcset');
      nestedImage.removeAttribute?.('data-src');
      nestedImage.removeAttribute?.('data-srcset');
    }

    card.dataset.witziArtwork = 'poster';
    card.dataset.witziPosterId = card.dataset.id;
    card.classList.add('witzi-poster-card');
    return true;
  }

  function markMissing(card) {
    card.dataset.witziArtwork = 'fallback';
    card.dataset.witziPosterId = card.dataset.id;
    card.classList.remove('witzi-poster-card');
  }

  function retryLater(delay = 1500) {
    window.clearTimeout(retryTimer);
    retryTimer = window.setTimeout(scheduleCards, delay);
  }

  function hasAppliedPoster(card, url) {
    const image = card.querySelector('.cardImageContainer');
    const nestedImage = image?.querySelector?.('img');
    const nestedImageMatches = !nestedImage || (
      (nestedImage.getAttribute?.('src') || nestedImage.src) === url
      && !nestedImage.getAttribute?.('srcset')
      && !nestedImage.getAttribute?.('data-src')
      && !nestedImage.getAttribute?.('data-srcset')
    );

    return card.dataset.witziArtwork === 'poster'
      && card.dataset.witziPosterId === card.dataset.id
      && image?.getAttribute('data-src') === url
      && image.style.backgroundImage.includes(url)
      && nestedImageMatches;
  }

  function needsProcessing(card) {
    const id = card.dataset.id;
    if (!id || pendingCards.has(card)) return false;

    const url = itemCache.get(id);
    if (url) return !hasAppliedPoster(card, url);

    return card.dataset.witziPosterId !== id
      || card.dataset.witziArtwork !== 'fallback'
      || Date.now() >= (retryAfter.get(id) || 0);
  }

  async function processCards() {
    const cards = [...document.querySelectorAll(CARD_SELECTOR)]
      .filter(needsProcessing);

    if (!cards.length) return;

    const api = getApiClient();
    if (!api) {
      retryLater();
      return;
    }

    cards.forEach((card) => pendingCards.add(card));
    const typeHints = new Map(cards.map((card) => [card.dataset.id, card.dataset.type]));

    try {
      const posters = await resolvePosters(api, typeHints);

      for (const card of cards) {
        const url = posters.get(card.dataset.id);
        if (!url || !applyPoster(card, url)) markMissing(card);
      }

      if (cards.some((card) => card.dataset.witziArtwork === 'fallback')) {
        retryLater(MISSING_RETRY_MS);
      }
    } catch (error) {
      cards.forEach(markMissing);
      console.warn('[witzi-posters] Poster lookup failed; retaining native card artwork.', error);
      retryLater();
    } finally {
      cards.forEach((card) => pendingCards.delete(card));
    }
  }

  function backdropUrl(image) {
    const attributeUrl = image?.getAttribute?.('data-url')
      || image?.getAttribute?.('data-src');
    if (attributeUrl) return attributeUrl;

    const backgroundImage = image?.style?.backgroundImage || '';
    const match = backgroundImage.match(/url\((['"]?)(.*?)\1\)/);
    return match?.[2] || null;
  }

  function latestBackdrop(container) {
    const images = container?.querySelectorAll?.('.backdropImage');
    return images?.length ? images[images.length - 1] : null;
  }

  function createBackdropLayer() {
    const layer = document.createElement('div');
    layer.classList.add('witzi-backdrop-cache-layer');
    layer.setAttribute('aria-hidden', 'true');
    return layer;
  }

  function ensureBackdropCache(container) {
    const parent = container?.parentNode;
    if (!parent || typeof document.createElement !== 'function') return null;

    if (!backdropState.cache) {
      const cache = document.createElement('div');
      cache.classList.add('witzi-backdrop-cache');
      cache.setAttribute('aria-hidden', 'true');

      backdropState.layers = [createBackdropLayer(), createBackdropLayer()];
      backdropState.layers.forEach((layer) => cache.appendChild(layer));
      backdropState.cache = cache;
    }

    if (backdropState.cache.parentNode !== parent
      || backdropState.cache.nextSibling !== container) {
      parent.insertBefore(backdropState.cache, container);
    }

    return backdropState.cache;
  }

  function syncBackdropVisibility(container, cache) {
    if (container.classList?.contains('hide')) {
      cache.classList.add('witzi-backdrop-cache-hidden');
    } else {
      cache.classList.remove('witzi-backdrop-cache-hidden');
    }
  }

  function activateBackdrop(container, url, requestId) {
    const cache = ensureBackdropCache(container);
    if (!cache || requestId !== backdropState.requestId) return;

    syncBackdropVisibility(container, cache);

    const nextIndex = backdropState.activeIndex === 0 ? 1 : 0;
    const isInitialBackdrop = backdropState.activeIndex < 0;
    const nextLayer = backdropState.layers[nextIndex];
    const previousLayer = backdropState.activeIndex >= 0
      ? backdropState.layers[backdropState.activeIndex]
      : null;

    nextLayer.classList.remove('witzi-backdrop-cache-active');
    nextLayer.style.backgroundImage = `url("${url.replace(/["\\]/g, '\\$&')}")`;
    nextLayer.setAttribute('data-url', url);
    if (isInitialBackdrop) cache.classList.add('witzi-backdrop-cache-initializing');

    window.requestAnimationFrame(() => {
      if (requestId !== backdropState.requestId) return;

      nextLayer.classList.add('witzi-backdrop-cache-active');
      previousLayer?.classList.remove('witzi-backdrop-cache-active');
      container.classList?.add('witzi-backdrop-cache-ready');
      cache.classList.add('witzi-backdrop-cache-ready');
      document.documentElement?.setAttribute?.('data-witzi-backdrop-cache', 'active');

      backdropState.activeIndex = nextIndex;
      backdropState.activeUrl = url;
      backdropState.pendingUrl = null;

      if (isInitialBackdrop) {
        window.requestAnimationFrame(() => {
          cache.classList.remove('witzi-backdrop-cache-initializing');
        });
      }

      window.clearTimeout(backdropState.cleanupTimer);
      backdropState.cleanupTimer = window.setTimeout(() => {
        if (previousLayer && previousLayer !== backdropState.layers[backdropState.activeIndex]) {
          previousLayer.style.backgroundImage = 'none';
          previousLayer.removeAttribute?.('data-url');
        }
      }, BACKDROP_TRANSITION_MS + 100);
    });
  }

  async function processBackdrop() {
    const container = document.querySelector?.(BACKDROP_SELECTOR);
    if (!container) return;

    if (backdropState.cache) syncBackdropVisibility(container, backdropState.cache);

    const url = backdropUrl(latestBackdrop(container));
    if (!url || url === backdropState.activeUrl || url === backdropState.pendingUrl) return;

    const requestId = ++backdropState.requestId;
    backdropState.pendingUrl = url;

    if (!await canLoad(url, BACKDROP_LOAD_TIMEOUT_MS)) {
      if (requestId === backdropState.requestId) backdropState.pendingUrl = null;
      return;
    }

    if (requestId === backdropState.requestId) activateBackdrop(container, url, requestId);
  }

  function detailContentCandidate(host, candidates, preferredCandidates = candidates) {
    const source = preferredCandidates.find((element) => !host.contains?.(element));
    const outsideHost = candidates.find((element) => !host.contains?.(element));
    const insideHost = candidates.find((element) => host.contains?.(element));

    return source || outsideHost || insideHost || null;
  }

  function syncDetailRibbonChildren(ribbon, content, managedContent) {
    managedContent.forEach((element) => {
      if (content.includes(element) || !ribbon.contains?.(element)) return;

      if (element.remove) element.remove();
      else element.parentNode?.removeChild?.(element);
    });

    const current = [...(ribbon.children || [])].filter((element) => content.includes(element));
    const alreadyCurrent = current.length === content.length
      && content.every((element, index) => (
        current[index] === element && element.parentNode === ribbon
      ));

    if (!alreadyCurrent) {
      content.forEach((element) => ribbon.insertBefore(element, null));
    }
  }

  function alignDetailRibbonOnce(page, ribbon) {
    if (alignedDetailRibbons.has(ribbon) || page?.classList?.contains?.('hide')) return;

    const poster = page?.querySelector?.('.detailImageContainer.hide-mobile .cardBox')
      || page?.querySelector?.('.detailImageContainer.hide-mobile .card');
    if (!poster?.getBoundingClientRect || !ribbon?.getBoundingClientRect || !ribbon.style?.setProperty) return;

    const posterRect = poster.getBoundingClientRect();
    const ribbonRect = ribbon.getBoundingClientRect();
    if (!posterRect.width || !posterRect.height || !ribbonRect.width || !ribbonRect.height) return;

    const offset = Math.round((posterRect.top - ribbonRect.top) * 100) / 100;
    if (!Number.isFinite(offset)) return;

    if (Math.abs(offset) > 0.5) {
      ribbon.style.setProperty(DETAIL_RIBBON_ALIGN_OFFSET, `${offset}px`);
    }

    alignedDetailRibbons.add(ribbon);
    page.setAttribute?.('data-witzi-ribbon-aligned', 'true');
  }

  function syncDetailRibbonPage(page) {
    const ribbon = page?.querySelector?.('.detailRibbon');
    if (!page || !ribbon) return;

    const infoCandidates = [...page.querySelectorAll('.infoWrapper')];
    const buttonCandidates = [...page.querySelectorAll('.mainDetailButtons')];
    const sectionCandidates = [...page.querySelectorAll('.detailSectionContent')];
    const groupCandidates = [...page.querySelectorAll('.itemDetailsGroup')];
    const clampedOverviews = [...page.querySelectorAll('.overview.detail-clamp-text')];
    const primaryClampedOverviews = [
      ...page.querySelectorAll('.detailPagePrimaryContent .overview.detail-clamp-text')
    ];
    const info = detailContentCandidate(ribbon, infoCandidates);
    const buttons = detailContentCandidate(ribbon, buttonCandidates);
    let overview = detailContentCandidate(ribbon, clampedOverviews, primaryClampedOverviews);
    if (!overview) {
      overview = detailContentCandidate(ribbon, [...page.querySelectorAll('.overview')]);
    }
    const sectionContent = overview?.closest?.('.detailSectionContent')
      || detailContentCandidate(
        ribbon,
        sectionCandidates,
        [...page.querySelectorAll('.detailPagePrimaryContent .detailSectionContent')]
      );
    const group = detailContentCandidate(
      ribbon,
      groupCandidates,
      [...page.querySelectorAll('.detailPagePrimaryContent .itemDetailsGroup')]
    );
    const content = [info, buttons, sectionContent, group].filter(Boolean);
    const managedContent = [
      ...infoCandidates,
      ...buttonCandidates,
      ...sectionCandidates,
      ...groupCandidates
    ];
    syncDetailRibbonChildren(ribbon, content, managedContent);

    const contentIsComplete = Boolean(
      sectionContent
      && group
      && sectionContent.parentNode === ribbon
      && group.parentNode === ribbon
    );

    if (contentIsComplete) {
      page.setAttribute('data-witzi-detail-content', 'active');
      alignDetailRibbonOnce(page, ribbon);
    } else if (content.length) {
      page.setAttribute('data-witzi-detail-content', 'pending');
    } else {
      page.removeAttribute?.('data-witzi-detail-content');
    }
  }

  function syncDetailRibbonContent() {
    document.querySelectorAll(DETAIL_PAGE_SELECTOR).forEach(syncDetailRibbonPage);
  }

  function syncVideoPlayback() {
    const active = Boolean(document.querySelector?.('.videoPlayerContainer'));
    if (active === videoPlaybackActive) return;

    videoPlaybackActive = active;
    if (active) {
      document.documentElement?.setAttribute?.('data-witzi-video-active', 'true');
    } else {
      document.documentElement?.removeAttribute?.('data-witzi-video-active');
    }
  }

  function scheduleDetail() {
    if (detailScheduled) return;
    detailScheduled = true;
    window.requestAnimationFrame(() => {
      detailScheduled = false;
      syncDetailRibbonContent();
    });
  }

  function scheduleCards() {
    if (cardScheduled) return;
    cardScheduled = true;
    window.requestAnimationFrame(() => {
      cardScheduled = false;
      void processCards();
    });
  }

  function scheduleBackdrop() {
    if (backdropScheduled) return;
    backdropScheduled = true;
    window.requestAnimationFrame(() => {
      backdropScheduled = false;
      void processBackdrop();
    });
  }

  function schedulePlayback() {
    if (playbackScheduled) return;
    playbackScheduled = true;
    window.requestAnimationFrame(() => {
      playbackScheduled = false;
      syncVideoPlayback();
    });
  }

  function scheduleMedia() {
    scheduleCards();
    scheduleBackdrop();
    schedulePlayback();
  }

  function schedule() {
    scheduleDetail();
    scheduleMedia();
  }

  function nodeMatchesOrContains(node, selector) {
    return Boolean(node?.matches?.(selector) || node?.querySelector?.(selector));
  }

  function targetIsWithin(target, selector) {
    return Boolean(target?.matches?.(selector) || target?.closest?.(selector));
  }

  function mutationNodesMatch(mutation, selector) {
    for (const node of mutation.addedNodes || []) {
      if (nodeMatchesOrContains(node, selector)) return true;
    }

    for (const node of mutation.removedNodes || []) {
      if (nodeMatchesOrContains(node, selector)) return true;
    }

    return false;
  }

  function mutationChangesScope(mutation, selector) {
    if (mutation?.type !== 'childList') return false;
    if (targetIsWithin(mutation.target, selector)) return true;

    return mutationNodesMatch(mutation, selector);
  }

  function mutationChangesCards(mutation) {
    if (mutation?.type === 'childList') {
      return mutation.target?.matches?.(CARD_SCOPE_SELECTOR)
        || mutationNodesMatch(mutation, CARD_LAYOUT_SELECTOR);
    }

    if (mutation?.type !== 'attributes') return false;

    const target = mutation.target;
    if (!targetIsWithin(target, CARD_SCOPE_SELECTOR)) return false;
    if (mutation.attributeName === 'data-id') return target?.matches?.('.card');

    if (mutation.attributeName === 'class' || mutation.attributeName === 'data-src') {
      return target?.matches?.('.cardImageContainer');
    }

    return (mutation.attributeName === 'src' || mutation.attributeName === 'srcset')
      && target?.matches?.('.cardImageContainer img');
  }

  function mutationChangesBackdrop(mutation) {
    if (mutationChangesScope(mutation, BACKDROP_SELECTOR)) return true;
    if (mutation?.type !== 'attributes') return false;

    const target = mutation.target;
    if (mutation.attributeName === 'class') return target?.matches?.(BACKDROP_SELECTOR);

    return (mutation.attributeName === 'data-src' || mutation.attributeName === 'data-url')
      && target?.matches?.('.backdropImage');
  }

  function mutationChangesPlayback(mutation) {
    return mutation?.type === 'childList'
      && mutationNodesMatch(mutation, '.videoPlayerContainer');
  }

  function mutationChangesDetailLayout(mutation) {
    if (mutation?.type === 'childList') {
      if (mutation.target?.matches?.(DETAIL_LAYOUT_PARENT_SELECTOR)) return true;

      return mutationNodesMatch(mutation, DETAIL_LAYOUT_SELECTOR);
    }

    return mutation?.type === 'attributes'
      && (mutation.attributeName === 'class' || mutation.attributeName === 'data-id')
      && mutation.target?.matches?.(DETAIL_LAYOUT_SELECTOR);
  }

  function start() {
    const observer = new MutationObserver((mutations = []) => {
      if (!mutations.length) {
        schedule();
        return;
      }

      let backdropChanged = false;
      let cardsChanged = false;
      let detailChanged = false;
      let playbackChanged = false;

      for (const mutation of mutations) {
        if (!cardsChanged) cardsChanged = mutationChangesCards(mutation);
        if (!backdropChanged) backdropChanged = mutationChangesBackdrop(mutation);
        if (!playbackChanged) playbackChanged = mutationChangesPlayback(mutation);
        if (!detailChanged) detailChanged = mutationChangesDetailLayout(mutation);
        if (cardsChanged && backdropChanged && playbackChanged && detailChanged) break;
      }

      if (cardsChanged) scheduleCards();
      if (backdropChanged) scheduleBackdrop();
      if (playbackChanged) schedulePlayback();
      if (detailChanged) scheduleDetail();
    });
    observer.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ['class', 'data-id', 'data-src', 'data-url', 'src', 'srcset'],
      childList: true,
      subtree: true
    });
    const settleDetailView = () => {
      schedule();
      [50, 250, 1000, 2000].forEach((delay) => window.setTimeout(schedule, delay));
    };

    window.addEventListener('viewshow', settleDetailView);
    window.addEventListener('pageshow', settleDetailView);
    settleDetailView();
  }

  function themeIsActive() {
    if (typeof window.getComputedStyle !== 'function') return true;

    try {
      return window.getComputedStyle(document.documentElement)
        ?.getPropertyValue('--witzi-theme-active')
        ?.trim() === '1';
    } catch {
      return false;
    }
  }

  function startWhenThemeIsReady() {
    if (started) return;

    if (!themeIsActive()) {
      document.documentElement?.setAttribute?.('data-witzi-posters', 'waiting');
      const delay = Math.min(
        THEME_WAIT_INITIAL_MS * (2 ** Math.min(themeWaitAttempts, 5)),
        THEME_WAIT_MAX_MS
      );
      themeWaitAttempts += 1;
      window.clearTimeout(themeWaitTimer);
      themeWaitTimer = window.setTimeout(startWhenThemeIsReady, delay);
      return;
    }

    started = true;
    window.clearTimeout(themeWaitTimer);
    document.documentElement?.setAttribute?.('data-witzi-posters', 'active');

    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', start, { once: true });
    } else {
      start();
    }
  }

  startWhenThemeIsReady();
}());
