/**
 * Witzi browser helper for Jellyfin Web.
 *
 * Jellyfin builds Continue Watching and Next Up with landscape artwork. CSS
 * cannot change the API-selected image URL, so this optional helper asks the
 * current Jellyfin ApiClient for each card's metadata and swaps in a real
 * poster. Episodes prefer their own portrait Primary poster (including one
 * generated by the Witzi server plugin), then the series' main Primary poster,
 * then a season/parent poster. Widescreen Primary captures are rejected. A
 * candidate must load successfully before it replaces Jellyfin's native
 * artwork, which remains visible as the last resort.
 *
 * The helper also keeps the last loaded backdrop in a two-layer cache outside
 * Jellyfin's backdrop container. Jellyfin clears that container between some
 * views, so the independent layers preserve the current image while the next
 * one loads, then crossfade without exposing the solid page background.
 */
(function witziPosterHelper() {
  'use strict';

  if (window.__witziPosterHelperLoaded) return;
  window.__witziPosterHelperLoaded = true;
  document.documentElement?.setAttribute?.('data-witzi-posters', 'active');

  const CARD_SELECTOR = '.itemsContainer[data-monitor*="videoplayback"][data-monitor*="markplayed"] .card[data-id]';
  const BACKDROP_SELECTOR = '.backdropContainer';
  const DETAIL_PAGE_SELECTOR = '#itemDetailPage';
  const DETAIL_RIBBON_CORRECTION = '--witzi-detail-ribbon-correction';
  const itemCache = new Map();
  const retryAfter = new Map();
  const pendingCards = new WeakSet();
  const MISSING_RETRY_MS = 30000;
  const POSTER_LOAD_TIMEOUT_MS = 8000;
  const BACKDROP_LOAD_TIMEOUT_MS = 12000;
  const BACKDROP_TRANSITION_MS = 900;
  const backdropState = {
    activeIndex: -1,
    activeUrl: null,
    cache: null,
    cleanupTimer: null,
    container: null,
    layers: [],
    pendingUrl: null,
    requestId: 0
  };
  let retryTimer;
  let scheduled = false;
  let videoPlaybackActive = false;

  function getApiClient() {
    return window.ApiClient || null;
  }

  function ownPoster(item) {
    const tag = item?.ImageTags?.Primary;
    const aspect = Number(item?.PrimaryImageAspectRatio);
    const isLandscapeFrame = Number.isFinite(aspect) && aspect > 1;
    return tag && item.Id && !isLandscapeFrame ? { id: item.Id, tag } : null;
  }

  function inheritedPosters(item) {
    const candidates = [
      item?.SeriesId && {
        id: item.SeriesId,
        tag: item.SeriesPrimaryImageTag || null
      },
      item?.ParentPrimaryImageItemId && {
        id: item.ParentPrimaryImageItemId,
        tag: item.ParentPrimaryImageTag || null
      },
      item?.SeasonId && { id: item.SeasonId, tag: null }
    ].filter(Boolean);

    return candidates.filter((poster, index) => (
      candidates.findIndex((candidate) => candidate.id === poster.id) === index
    ));
  }

  function posterUrl(api, poster) {
    const options = {
      type: 'Primary',
      maxWidth: 600,
      quality: 90
    };

    if (poster.tag) options.tag = poster.tag;

    return typeof api.getScaledImageUrl === 'function'
      ? api.getScaledImageUrl(poster.id, options)
      : api.getImageUrl(poster.id, options);
  }

  async function fetchItems(api, ids) {
    const userId = api.getCurrentUserId?.();
    if (!userId || typeof api.getItems !== 'function') {
      throw new Error('Jellyfin ApiClient is not ready');
    }

    const response = await api.getItems(userId, {
      Ids: ids.join(','),
      Fields: 'PrimaryImageAspectRatio,ParentId',
      EnableImages: true,
      EnableImageTypes: 'Primary',
      ImageTypeLimit: 1
    });

    return response?.Items || [];
  }

  function isEpisode(item, typeHint) {
    return typeHint?.toLowerCase() === 'episode'
      || item?.Type?.toLowerCase() === 'episode'
      || Boolean(item?.SeriesId);
  }

  function canLoad(url, timeoutMs = POSTER_LOAD_TIMEOUT_MS) {
    return new Promise((resolve) => {
      const image = new Image();
      let settled = false;

      const finish = (loaded) => {
        if (settled) return;
        settled = true;
        window.clearTimeout(timeout);
        image.onload = null;
        image.onerror = null;
        resolve(loaded);
      };

      const timeout = window.setTimeout(() => finish(false), timeoutMs);
      image.onload = () => finish(true);
      image.onerror = () => finish(false);
      image.src = url;
    });
  }

  async function firstLoadablePoster(api, candidates) {
    for (const poster of candidates) {
      const url = posterUrl(api, poster);
      if (await canLoad(url)) return url;
    }

    return null;
  }

  async function resolvePosters(api, typeHints) {
    const ids = [...typeHints.keys()];
    const now = Date.now();
    const missingIds = ids.filter((id) => (
      !itemCache.has(id) && now >= (retryAfter.get(id) || 0)
    ));

    if (missingIds.length) {
      const items = await fetchItems(api, missingIds);
      const itemsById = new Map(items.map((item) => [item.Id, item]));

      await Promise.all(missingIds.map(async (id) => {
        const item = itemsById.get(id);
        const own = item && ownPoster(item);
        const candidates = isEpisode(item, typeHints.get(id))
          ? [own, ...inheritedPosters(item)].filter(Boolean)
          : own ? [own] : [];
        const url = await firstLoadablePoster(api, candidates);

        if (url) {
          itemCache.set(id, url);
          retryAfter.delete(id);
        } else {
          retryAfter.set(id, Date.now() + MISSING_RETRY_MS);
        }
      }));
    }

    return new Map(ids.map((id) => [id, itemCache.get(id) || null]));
  }

  function applyPoster(card, url) {
    const image = card.querySelector('.cardImageContainer');
    if (!image) return false;

    image.setAttribute('data-src', url);
    image.removeAttribute?.('data-blurhash');
    image.classList?.remove('lazy');
    image.style.backgroundImage = `url("${url.replace(/["\\]/g, '\\$&')}")`;
    image.style.backgroundPosition = 'center';
    image.style.backgroundRepeat = 'no-repeat';
    image.style.backgroundSize = 'cover';

    const nestedImage = image.querySelector('img');
    if (nestedImage) {
      nestedImage.src = url;
      nestedImage.removeAttribute?.('srcset');
      nestedImage.removeAttribute?.('data-src');
      nestedImage.removeAttribute?.('data-srcset');
    }

    card.dataset.witziArtwork = 'poster';
    card.dataset.witziPosterId = card.dataset.id;
    card.classList.add('witzi-poster-card');
    card.classList.remove('witzi-poster-pending');
    card.classList.remove('witzi-no-poster-card');
    card.classList.remove('witzi-native-fallback');
    return true;
  }

  function markPending(card) {
    card.classList.add('witzi-poster-pending');
  }

  function markMissing(card) {
    card.dataset.witziArtwork = 'fallback';
    card.dataset.witziPosterId = card.dataset.id;
    card.classList.remove('witzi-poster-card');
    card.classList.remove('witzi-poster-pending');
    card.classList.add('witzi-native-fallback');
  }

  function retryLater(delay = 1500) {
    window.clearTimeout(retryTimer);
    retryTimer = window.setTimeout(schedule, delay);
  }

  function hasAppliedPoster(card, url) {
    const image = card.querySelector('.cardImageContainer');
    return card.dataset.witziArtwork === 'poster'
      && card.dataset.witziPosterId === card.dataset.id
      && image?.getAttribute('data-src') === url
      && image.style.backgroundImage.includes(url);
  }

  function needsProcessing(card) {
    const id = card.dataset.id;
    if (!id || pendingCards.has(card)) return false;

    const url = itemCache.get(id);
    if (url) return !hasAppliedPoster(card, url);

    return card.dataset.witziPosterId !== id
      || card.dataset.witziArtwork !== 'fallback'
      || Date.now() >= (retryAfter.get(id) || 0);
  }

  async function processCards() {
    const cards = [...document.querySelectorAll(CARD_SELECTOR)]
      .filter(needsProcessing);

    if (!cards.length) return;

    cards.forEach(markPending);

    const api = getApiClient();
    if (!api) {
      retryLater();
      return;
    }

    cards.forEach((card) => pendingCards.add(card));
    const typeHints = new Map(cards.map((card) => [card.dataset.id, card.dataset.type]));

    try {
      const posters = await resolvePosters(api, typeHints);

      for (const card of cards) {
        const url = posters.get(card.dataset.id);
        if (!url || !applyPoster(card, url)) markMissing(card);
      }

      if (cards.some((card) => card.dataset.witziArtwork === 'fallback')) {
        retryLater(MISSING_RETRY_MS);
      }
    } catch (error) {
      cards.forEach(markMissing);
      console.warn('[witzi-posters] Poster lookup failed; retaining native card artwork.', error);
      retryLater();
    } finally {
      cards.forEach((card) => pendingCards.delete(card));
    }
  }

  function backdropUrl(image) {
    const attributeUrl = image?.getAttribute?.('data-url')
      || image?.getAttribute?.('data-src');
    if (attributeUrl) return attributeUrl;

    const backgroundImage = image?.style?.backgroundImage || '';
    const match = backgroundImage.match(/url\((['"]?)(.*?)\1\)/);
    return match?.[2] || null;
  }

  function latestBackdrop(container) {
    const images = [...(container?.querySelectorAll?.('.backdropImage') || [])];
    return images.length ? images[images.length - 1] : null;
  }

  function createBackdropLayer() {
    const layer = document.createElement('div');
    layer.classList.add('witzi-backdrop-cache-layer');
    layer.setAttribute('aria-hidden', 'true');
    return layer;
  }

  function ensureBackdropCache(container) {
    const parent = container?.parentNode;
    if (!parent || typeof document.createElement !== 'function') return null;

    if (!backdropState.cache) {
      const cache = document.createElement('div');
      cache.classList.add('witzi-backdrop-cache');
      cache.setAttribute('aria-hidden', 'true');

      backdropState.layers = [createBackdropLayer(), createBackdropLayer()];
      backdropState.layers.forEach((layer) => cache.appendChild(layer));
      backdropState.cache = cache;
    }

    if (backdropState.cache.parentNode !== parent
      || backdropState.cache.nextSibling !== container) {
      parent.insertBefore(backdropState.cache, container);
    }

    backdropState.container = container;
    return backdropState.cache;
  }

  function syncBackdropVisibility(container, cache) {
    if (container.classList?.contains('hide')) {
      cache.classList.add('witzi-backdrop-cache-hidden');
    } else {
      cache.classList.remove('witzi-backdrop-cache-hidden');
    }
  }

  function activateBackdrop(container, url, requestId) {
    const cache = ensureBackdropCache(container);
    if (!cache || requestId !== backdropState.requestId) return;

    syncBackdropVisibility(container, cache);

    const nextIndex = backdropState.activeIndex === 0 ? 1 : 0;
    const isInitialBackdrop = backdropState.activeIndex < 0;
    const nextLayer = backdropState.layers[nextIndex];
    const previousLayer = backdropState.activeIndex >= 0
      ? backdropState.layers[backdropState.activeIndex]
      : null;

    nextLayer.classList.remove('witzi-backdrop-cache-active');
    nextLayer.style.backgroundImage = `url("${url.replace(/["\\]/g, '\\$&')}")`;
    nextLayer.setAttribute('data-url', url);
    if (isInitialBackdrop) cache.classList.add('witzi-backdrop-cache-initializing');

    window.requestAnimationFrame(() => {
      if (requestId !== backdropState.requestId) return;

      nextLayer.classList.add('witzi-backdrop-cache-active');
      previousLayer?.classList.remove('witzi-backdrop-cache-active');
      container.classList?.add('witzi-backdrop-cache-ready');
      cache.classList.add('witzi-backdrop-cache-ready');
      document.documentElement?.setAttribute?.('data-witzi-backdrop-cache', 'active');

      backdropState.activeIndex = nextIndex;
      backdropState.activeUrl = url;
      backdropState.pendingUrl = null;

      if (isInitialBackdrop) {
        window.requestAnimationFrame(() => {
          cache.classList.remove('witzi-backdrop-cache-initializing');
        });
      }

      window.clearTimeout(backdropState.cleanupTimer);
      backdropState.cleanupTimer = window.setTimeout(() => {
        if (previousLayer && previousLayer !== backdropState.layers[backdropState.activeIndex]) {
          previousLayer.style.backgroundImage = 'none';
          previousLayer.removeAttribute?.('data-url');
        }
      }, BACKDROP_TRANSITION_MS + 100);
    });
  }

  async function processBackdrop() {
    const container = document.querySelector?.(BACKDROP_SELECTOR);
    if (!container) return;

    if (backdropState.cache) syncBackdropVisibility(container, backdropState.cache);

    const url = backdropUrl(latestBackdrop(container));
    if (!url || url === backdropState.activeUrl || url === backdropState.pendingUrl) return;

    const requestId = ++backdropState.requestId;
    backdropState.pendingUrl = url;

    if (!await canLoad(url, BACKDROP_LOAD_TIMEOUT_MS)) {
      if (requestId === backdropState.requestId) backdropState.pendingUrl = null;
      return;
    }

    if (requestId === backdropState.requestId) activateBackdrop(container, url, requestId);
  }

  function detailContentCandidate(page, host, selector, sourceSelector = selector) {
    const sourceCandidates = [...(page.querySelectorAll?.(sourceSelector) || [])];
    const source = sourceCandidates.find((element) => !host.contains?.(element));
    const candidates = [...(page.querySelectorAll?.(selector) || [])];
    const outsideHost = candidates.find((element) => !host.contains?.(element));
    const insideHost = candidates.find((element) => host.contains?.(element));

    return source || outsideHost || insideHost || page.querySelector?.(selector);
  }

  function syncDetailRibbonChildren(host, content) {
    content.forEach((element, index) => {
      const reference = host.children?.[index] || null;
      if (reference !== element) host.insertBefore(element, reference);
    });

    [...(host.children || [])].forEach((element) => {
      if (!content.includes(element)) {
        if (element.remove) element.remove();
        else host.removeChild?.(element);
      }
    });
  }

  function detailPageHasScrolled(page) {
    // Jellyfin can preserve scroll offsets on the shared page ancestors while
    // a newly shown detail page itself is still at its top. Those unrelated
    // offsets must not suppress the initial poster/ribbon alignment.
    return Number(page?.scrollTop) > 1;
  }

  function alignDetailRibbonPage(page, ribbon) {
    const poster = page?.querySelector?.('.detailImageContainer.hide-mobile .cardBox')
      || page?.querySelector?.('.detailImageContainer.hide-mobile .card');
    const style = ribbon?.style;
    if (!poster?.getBoundingClientRect || !ribbon?.getBoundingClientRect || !style?.setProperty) return;
    if (detailPageHasScrolled(page)) return;

    const posterRect = poster.getBoundingClientRect();
    const ribbonRect = ribbon.getBoundingClientRect();
    if (!posterRect.width || !posterRect.height || !ribbonRect.width || !ribbonRect.height) return;

    const delta = posterRect.top - ribbonRect.top;
    if (!Number.isFinite(delta)) return;

    if (Math.abs(delta) > 0.5) {
      const current = Number.parseFloat(style.getPropertyValue?.(DETAIL_RIBBON_CORRECTION)) || 0;
      const correction = Math.round((current + delta) * 100) / 100;
      style.setProperty(DETAIL_RIBBON_CORRECTION, `${correction}px`);
    }

    page.setAttribute?.('data-witzi-ribbon-aligned', 'true');
  }

  function syncDetailRibbonPage(page) {
    const ribbon = page?.querySelector?.('.detailRibbon');
    if (!page || !ribbon || typeof document.createElement !== 'function') return;

    let host = ribbon.querySelector?.('.witzi-ribbon-content');
    if (!host) {
      host = document.createElement('div');
      host.classList.add('witzi-ribbon-content');
      ribbon.insertBefore(host, ribbon.querySelector?.('.mainDetailButtons') || null);
    }

    const info = detailContentCandidate(page, host, '.infoWrapper');
    const buttons = detailContentCandidate(page, host, '.mainDetailButtons');
    const sectionContent = detailContentCandidate(
      page,
      host,
      '.detailSectionContent',
      '.detailPagePrimaryContent > .detailSection > .detailSectionContent'
    );
    const group = detailContentCandidate(
      page,
      host,
      '.itemDetailsGroup',
      '.detailPagePrimaryContent > .detailSection > .itemDetailsGroup'
    );
    const content = [info, buttons, sectionContent, group].filter(Boolean);
    const current = [...(host.children || [])];
    const alreadyCurrent = current.length === content.length
      && content.every((element, index) => current[index] === element);

    if (!alreadyCurrent) syncDetailRibbonChildren(host, content);

    const contentIsComplete = Boolean(
      sectionContent
      && group
      && sectionContent.parentNode === host
      && group.parentNode === host
    );

    if (contentIsComplete) {
      page.setAttribute('data-witzi-detail-content', 'active');
    } else if (content.length) {
      page.setAttribute('data-witzi-detail-content', 'pending');
    } else {
      page.removeAttribute?.('data-witzi-detail-content');
    }

    alignDetailRibbonPage(page, ribbon);
  }

  function syncDetailRibbonContent() {
    const pages = [...(document.querySelectorAll?.(DETAIL_PAGE_SELECTOR) || [])];
    const fallback = document.querySelector?.(DETAIL_PAGE_SELECTOR);
    if (!pages.length && fallback) pages.push(fallback);
    pages.forEach(syncDetailRibbonPage);
  }

  function syncVideoPlayback() {
    const active = Boolean(document.querySelector?.('.videoPlayerContainer'));
    if (active === videoPlaybackActive) return;

    videoPlaybackActive = active;
    if (active) {
      document.documentElement?.setAttribute?.('data-witzi-video-active', 'true');
    } else {
      document.documentElement?.removeAttribute?.('data-witzi-video-active');
    }
  }

  function schedule() {
    if (scheduled) return;
    scheduled = true;
    window.requestAnimationFrame(() => {
      scheduled = false;
      syncVideoPlayback();
      syncDetailRibbonContent();
      void processCards();
      void processBackdrop();
    });
  }

  function start() {
    const observer = new MutationObserver(schedule);
    observer.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ['class', 'data-id', 'data-src', 'data-url', 'style'],
      childList: true,
      subtree: true
    });
    const settleDetailView = () => {
      schedule();
      [50, 250, 1000, 2000].forEach((delay) => window.setTimeout(schedule, delay));
    };

    window.addEventListener('viewshow', settleDetailView);
    window.addEventListener('pageshow', settleDetailView);
    window.addEventListener('resize', schedule);
    settleDetailView();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', start, { once: true });
  } else {
    start();
  }
}());
